const PREFIX = 'snippets';

const FETCH_SNIPPETS = 'FETCH_SNIPPETS';
const FETCH_SNIPPET = 'FETCH_SNIPPET';
const ADD_NEW_SNIPPET = 'ADD_NEW_SNIPPET';
const CLEAR_CODE_SNIPPET = 'CLEAR_CODE_SNIPPET';
const UPDATE_SNIPPET = 'UPDATE_SNIPPET';
const REMOVE_SNIPPET = 'REMOVE_SNIPPET';

export default {
  FETCH_SNIPPETS: `${PREFIX}/${FETCH_SNIPPETS}`,
  FETCH_SNIPPET: `${PREFIX}/${FETCH_SNIPPET}`,
  ADD_NEW_SNIPPET: `${PREFIX}/${ADD_NEW_SNIPPET}`,
  CLEAR_CODE_SNIPPET: `${PREFIX}/${CLEAR_CODE_SNIPPET}`,
  UPDATE_SNIPPET: `${PREFIX}/${UPDATE_SNIPPET}`,
  REMOVE_SNIPPET: `${PREFIX}/${REMOVE_SNIPPET}`,
};
