const PREFIX = 'filters';

const CHANGE_SORT_BY = 'CHANGE_SORT_BY';
const UPDATE_FILTERS_DATA = 'UPDATE_FILTERS_DATA';

export default {
  CHANGE_SORT_BY: `${PREFIX}/${CHANGE_SORT_BY}`,
  UPDATE_FILTERS_DATA: `${PREFIX}/${UPDATE_FILTERS_DATA}`,
};
