const PREFIX = 'filters';

const CHANGE_FILTERS_FIELD = 'CHANGE_FILTERS_FIELD';
const UPDATE_FILTERS_DATA = 'UPDATE_FILTERS_DATA';
const CLEAR_FILTERS = 'CLEAR_FILTERS';

export default {
  CHANGE_FILTERS_FIELD: `${PREFIX}/${CHANGE_FILTERS_FIELD}`,
  UPDATE_FILTERS_DATA: `${PREFIX}/${UPDATE_FILTERS_DATA}`,
  CLEAR_FILTERS: `${PREFIX}/${CLEAR_FILTERS}`,
};
